# Generated by Django 4.1 on 2024-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_comparison", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codecomparisonhistory",
            name="diff_content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
