# Generated by Django 5.0.7 on 2024-07-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_comparison', '0002_codecomparisonhistory_diff_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecomparisonhistory',
            name='diff_content_html',
            field=models.TextField(default=''),
        ),
    ]
