# Generated by Django 5.0.7 on 2024-07-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_comparison", "0004_codecomparisonhistory_check_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codecomparisonhistory",
            name="check_type",
            field=models.CharField(
                choices=[("normal", "普通查重"), ("ast", "抽象语法树查重")],
                default=("normal", "普通查重"),
                max_length=20,
            ),
        ),
    ]
